### ISSUE TITLE
自分以外のプロジェクトを削除できてしまう？？

### ISSUE THREAD

**Issue by SkBoyZ** [hackz-inc/topaz.dev#8]
## バグ詳細
- プロジェクト詳細画面で編集ボタンが押せるようになっている。
- 編集画面で左上に「投稿削除ボタン」があり、押せてしまうと思われる。
  - 押して削除してしまうとまずいので、確かめてはいない。。

**Comment by moririn772** [comment]
ありがとうございます 🙏 
APIがログインユーザーと投稿の作成ユーザーが一致しない限り削除できない仕様なので、いたずらに押しても消せることはないのですが出ちゃうのはマズいですね...

**Comment by SkBoyZ** [comment]
@moririn772 
押して消えないのであれば、ひとまずは安心しました！
見えちゃうのはよくないと思うので、投稿者のチェックは入れた方が良いかと思います。。

**Comment by apple-yagi** [comment]
@kkmory このバグなんですけど、フロントエンド（Nuxt）側でもっているCurrentUserの情報がFirebaseに基づいたものに対して、APIから取得できるポートフォリオの投稿者情報はデータベースのUidに基づいたものなので、投稿者チェックがフロントエンド側でできないです。

システム修正案
1. APIから取得できるポートフォリオの投稿者情報にFirebaseのUidを含める
2. マイページからしかポートフォリオの編集をできなくする

**Comment by kkmory** [comment]
とりあえず突貫工事ですが、ボタンの表示の挙動は修正しました。

> APIから取得できるポートフォリオの投稿者情報にFirebaseのUidを含める
> マイページからしかポートフォリオの編集をできなくする

みたく、根本的な解決になる感じに設計変えないとですが一旦解決したのでCloseします。
お二方ありがとうございます！
